name: sociable
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auth_repository:
    path: repositories/auth
  form_validator:
    path: packages/form_validator
  user_repository:
    path: repositories/user
  bloc: ^8.1.2
  cloud_firestore: ^4.8.5
  equatable: ^2.0.5
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl_phone_field: ^3.2.0
  pinput: ^3.0.0
  formz: ^0.6.0
  google_sign_in: ^6.1.4
  flow_builder: ^0.0.9
  image_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
